### ISSUE TITLE
词云重构

### ISSUE THREAD

**Issue by StarWishsama** [ELQASASystem/app#4]
让词云通过 Channel 传输分词后文本，而不是直接 for-loop。

- [x] 移动词云至 /websocket 下
- [x] 修改至符合 OOP 样式 (类似于 websocket/question.go)
- [x] 使用管道传输词汇
  - 管道放置在 ~~srv~~ word_stat.go 下
  - #handleWordStat 使用管道传输

**Comment by qianjunakasumi** [comment]
请解决包循环问题
https://github.com/kongchuanhujiao/CityServer/pull/5/checks?check_run_id=1487606075
#5 Go / Build (pull_request) Failing after 14s — Build
